from __future__ import annotations

"""Vendored from autoresearch-sboss@6e01155a5932a5456995465ae761db8057f87089 — examples/ar-cuit/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

CUIT_LENGTH = 11
_SEPARATOR_RE = re.compile(r"[\s\-]")
_ALL_DIGITS_RE = re.compile(r"^[0-9]+$")
_ALL_SAME_RE = re.compile(r"^(\d)\1{10}$")  # 11 of the same digit

# Weights for the mod-11 check (per AFIP spec)
_CUIT_WEIGHTS = (5, 4, 3, 2, 7, 6, 5, 4, 3, 2)

# Known CUIT/CUIL type prefixes
_KNOWN_PREFIXES = frozenset({"20", "23", "24", "25", "26", "27", "30", "33", "34"})


def normalize_cuit(value: Any) -> str:
    """Strip whitespace + hyphens. Returns "" for null/None.

    Examples:
      '20-12345678-6'  -> '20123456786'
      '20 12345678 6'  -> '20123456786'
      '20123456786'    -> '20123456786'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value))


def _default_check_digit(cuit: str) -> bool:
    """Default check-digit verifier — accepts any 11-digit string.

    Replaced with the CUIT mod-11 algorithm. Apply weights
    [5, 4, 3, 2, 7, 6, 5, 4, 3, 2] to the first 10 digits, sum,
    mod 11. Check = (11 - (sum mod 11)) mod 11. The 11th digit
    should match the check.
    """
    digits = [int(c) for c in cuit]
    s = sum(d * w for d, w in zip(digits, _CUIT_WEIGHTS))
    check = (11 - (s % 11)) % 11
    return check == digits[10]



def validate_cuit(value: Any, *, check_digit_verifier=None) -> dict[str, Any]:
    """Validate an Argentina CUIT/CUIL. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        check_digit_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the check-digit error. Defaults to the local
            _default_check_digit (which currently accepts everything).

    Returns:
        { ok: bool, normalized: str, "error": str | None }
    """
    verifier = check_digit_verifier if check_digit_verifier is not None else _default_check_digit

    normalized = normalize_cuit(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "CUIT is required"}
    if not _ALL_DIGITS_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "CUIT must contain only digits"}
    if len(normalized) != CUIT_LENGTH:
        return {"ok": False, "normalized": normalized, "error": f"CUIT must be {CUIT_LENGTH} digits, got {len(normalized)}"}
    if _ALL_SAME_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "CUIT is invalid (all digits are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "CUIT check digit is invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "cuit": "<raw CUIT string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_cuit(input_data.get("cuit"))
