from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/cl-rut/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

RUT_MIN_BODY = 7
RUT_MAX_BODY = 8
_SEPARATOR_RE = re.compile(r"[\s.\-]")  # strip space, dot, hyphen
_ALL_SAME_BODY_RE = re.compile(r"^(\d)\1{6,7}$")  # 7 or 8 of the same digit
_BODY_AND_CHECK_RE = re.compile(r"^(\d{7,8})([0-9K])$")

# Weights for the mod-11 check (per SII spec), applied right-to-left
_RUT_WEIGHTS = (2, 3, 4, 5, 6, 7, 2, 3)


def normalize_rut(value: Any) -> str:
    """Strip whitespace + common separators. Returns "" for null/None.

    Examples:
      '18550123-K'  -> '18550123K'
      '18.550.123-K' -> '18550123K'
      '18550123 K'  -> '18550123K'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value)).upper()


def _default_check_digit(rut: str) -> bool:
    """Default check-digit verifier (currently accepts any 7-8 digit + check string).

    This is the documented TODO seam. The official RUT mod-11 algorithm
    goes here. The agent's main lever is to implement this correctly.

    Args:
        rut: a 8-9 char string (7-8 digit body + check) that has already
            passed length / digits / non-degenerate checks.

    Returns:
        True if the check digit is valid, False if not.
    """
    # TODO: implement official SII RUT mod-11 check-digit algorithm.
    # See: https://www.sii.cl/
    return True


def validate_rut(value: Any, *, check_digit_verifier=None) -> dict[str, Any]:
    """Validate a Chile RUT. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        check_digit_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the check-digit error. Defaults to the local
            _default_check_digit (which currently accepts everything).

    Returns:
        { ok: bool, normalized: str, "error": str | None }
    """
    verifier = check_digit_verifier if check_digit_verifier is not None else _default_check_digit

    normalized = normalize_rut(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "RUT is required"}
    if not _BODY_AND_CHECK_RE.match(normalized):
        return {
            "ok": False,
            "normalized": normalized,
            "error": "RUT must be 7-8 digits followed by a check digit (0-9 or K)",
        }
    body = normalized[:-1]
    if _ALL_SAME_BODY_RE.match(body):
        return {"ok": False, "normalized": normalized, "error": "RUT is invalid (all digits in the body are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "RUT check digit is invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "rut": "<raw RUT string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_rut(input_data.get("rut"))
