from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/cnpj/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

CNPJ_LENGTH = 14
# Format: 2.3.3/4-2 with the slash between 8th and 9th digit and dash before check digits.
# Separators: space, dot, slash, dash (or none).
_SEPARATOR_RE = re.compile(r"[\s./\-]")
_ALL_DIGITS_RE = re.compile(r"^[0-9]+$")
_ALL_SAME_RE = re.compile(r"^(\d)\1{13}$")  # 14 of the same digit


def normalize_cnpj(value: Any) -> str:
    """Strip ALL separators (space, dot, slash, dash). Returns "" for null/None.

    Examples:
      '11.222.333/0001-81'  -> '11222333000181'
      '11222333/0001-81'     -> '11222333000181'
      '11 222 333 0001 81'   -> '11222333000181'
      '11222333000181'        -> '11222333000181'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value))


def _default_check_digit(cnpj: str) -> bool:
    """Default check-digit verifier — accepts any 14-digit string.

    Replaced with the real mod-11 algorithm (Receita Federal spec):
    DV1 uses weights [5,4,3,2,9,8,7,6,5,4,3,2] on first 12 digits.
    DV2 uses weights [6,5,4,3,2,9,8,7,6,5,4,3,2] on first 13 digits (12 + DV1).
    """
    if len(cnpj) != CNPJ_LENGTH:
        return False
    digits = [int(c) for c in cnpj]

    # DV1: weights [5,4,3,2,9,8,7,6,5,4,3,2] on first 12 digits
    w1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
    s1 = sum(w1[i] * digits[i] for i in range(12))
    dv1 = 0 if (s1 % 11) < 2 else 11 - (s1 % 11)
    if dv1 != digits[12]:
        return False

    # DV2: weights [6,5,4,3,2,9,8,7,6,5,4,3,2] on first 13 digits (12 + DV1)
    w2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
    s2 = sum(w2[i] * digits[i] for i in range(13))
    dv2 = 0 if (s2 % 11) < 2 else 11 - (s2 % 11)
    return dv2 == digits[13]



def validate_cnpj(value: Any, *, check_digit_verifier=None) -> dict[str, Any]:
    """Validate a CNPJ. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        check_digit_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the check-digit error. Defaults to the local _default_check_digit.

    Returns:
        { ok: bool, normalized: str, error: str | None }
    """
    verifier = check_digit_verifier if check_digit_verifier is not None else _default_check_digit

    normalized = normalize_cnpj(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "CNPJ is required"}
    if not _ALL_DIGITS_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "CNPJ must contain only digits"}
    if len(normalized) != CNPJ_LENGTH:
        return {"ok": False, "normalized": normalized, "error": f"CNPJ must be {CNPJ_LENGTH} digits, got {len(normalized)}"}
    if _ALL_SAME_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "CNPJ is invalid (all digits are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "CNPJ check digits are invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "cnpj": "<raw CNPJ string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_cnpj(input_data.get("cnpj"))
