from __future__ import annotations

"""Vendored from autoresearch-sboss@6e01155a5932a5456995465ae761db8057f87089 — examples/in-pan/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

PAN_LENGTH = 10
_SEPARATOR_RE = re.compile(r"[\s\-]")
_ALL_LETTERS_RE = re.compile(r"^[A-Z]+$")
_ALL_SAME_RE = re.compile(r"^(\w)\1{9}$")  # 10 of the same char
# Standard PAN structure: 3 letters + kind + letter + 4 digits + letter
# Kind codes: P (individual), C (company), H (HUF), F (firm), A (AOP), T (trust),
# B (BOI), L (local authority), J (artificial juridical person), G (government)
_PAN_STRUCTURE_RE = re.compile(r"^[A-Z]{3}[CPHFATBLJG][A-Z][0-9]{4}[A-Z]$")

# Recognized PAN kind codes (4th character)
_KIND_CODES = frozenset("CPHFATBLJG")


def normalize_pan(value: Any) -> str:
    """Strip whitespace + hyphens, uppercase. Returns "" for null/None.

    Examples:
      'AAAPA1234A'  -> 'AAAPA1234A'
      'aaapa 1234 a' -> 'AAAPA1234A'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value)).upper()


def _default_check_digit(pan: str) -> bool:
    """Default check-digit verifier — accepts any well-formed string.

    Replaced with the PAN format check: 4th character must be one of the
    recognized kind codes (P/C/H/F/A/T/B/L/J/G).
    """
    return _PAN_STRUCTURE_RE.match(pan) is not None



def validate_pan(value: Any, *, check_digit_verifier=None) -> dict[str, Any]:
    """Validate an India PAN. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        check_digit_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the check-digit error. Defaults to the local
            _default_check_digit (which currently accepts everything).

    Returns:
        { ok: bool, normalized: str, "error": str | None }
    """
    verifier = check_digit_verifier if check_digit_verifier is not None else _default_check_digit

    normalized = normalize_pan(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "PAN is required"}
    if len(normalized) != PAN_LENGTH:
        return {"ok": False, "normalized": normalized, "error": f"PAN must be {PAN_LENGTH} characters, got {len(normalized)}"}
    if _ALL_SAME_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "PAN is invalid (all characters are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "PAN format is invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "pan": "<raw PAN string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_pan(input_data.get("pan"))
