from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/kr-brn/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

BRN_LENGTH = 10
_SEPARATOR_RE = re.compile(r"[\s\-]")
_ALL_DIGITS_RE = re.compile(r"^[0-9]+$")
_ALL_SAME_RE = re.compile(r"^(\d)\1{9}$")  # 10 of the same digit
# Canonical 3-2-5 format: "123-45-67890" → after normalize: "1234567890"
_CANONICAL_3_2_5_RE = re.compile(r"^\d{3}-\d{2}-\d{5}$")


def normalize_brn(value: Any) -> str:
    """Strip whitespace + hyphens. Returns "" for null/None.

    Examples:
      '123-45-67890' -> '1234567890'
      '123 45 67890' -> '1234567890'
      '1234567890'   -> '1234567890'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value))


def _default_kind(brn: str) -> bool:
    """Default kind verifier (currently accepts any 10-digit string).

    This is the documented TODO seam. The NTS publishes the kind
    classification rules (first 3 digits = tax office, next 2 = business
    type). The agent's main lever is to implement this correctly.

    Args:
        brn: a 10-digit string that has already passed length / digits / non-degenerate checks.

    Returns:
        True if the kind structure is valid, False if not.
    """
    # TODO: implement official NTS BRN kind validation.
    # See: https://www.nts.go.kr/
    return True


def validate_brn(value: Any, *, kind_verifier=None) -> dict[str, Any]:
    """Validate a Korea BRN. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        kind_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the kind error. Defaults to the local
            _default_kind (which currently accepts everything).

    Returns:
        { ok: bool, normalized: str, "error": str | None }
    """
    verifier = kind_verifier if kind_verifier is not None else _default_kind

    normalized = normalize_brn(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "BRN is required"}
    if not _ALL_DIGITS_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "BRN must contain only digits"}
    if len(normalized) != BRN_LENGTH:
        return {"ok": False, "normalized": normalized, "error": f"BRN must be {BRN_LENGTH} digits, got {len(normalized)}"}
    if _ALL_SAME_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "BRN is invalid (all digits are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "BRN format is invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "brn": "<raw BRN string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_brn(input_data.get("brn"))
