from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/model-policy/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



from typing import Any

MODEL_KEYS = ("default", "copilot", "transform", "finance", "crm", "docs")
MODULES = frozenset({"finance", "crm", "docs"})
ASPECTS = frozenset({"copilot", "transform"})


def _pick(policy: dict[str, Any], key: str) -> str:
    """Return policy[key] if it's a non-empty string after trim, else ""."""
    val = policy.get(key) if isinstance(policy, dict) else None
    if isinstance(val, str):
        trimmed = val.strip()
        return trimmed if trimmed else ""
    return ""


def resolve_model(policy: dict[str, Any] | None = None,
                  ctx: dict[str, Any] | None = None) -> str:
    """Faithful port of resolveModelForRequest() from src/model-policy.js.

    Returns the model id (or "" for auto). Does NOT return source/chain.
    """
    if policy is None:
        policy = {}
    if ctx is None:
        ctx = {}
    module = ctx.get("module")
    aspect = ctx.get("aspect")

    if module and module in MODULES:
        m = _pick(policy, module)
        if m:
            return m
    if aspect and aspect in ASPECTS:
        a = _pick(policy, aspect)
        if a:
            return a
    return _pick(policy, "default")


# ---------------------------------------------------------------------------
# run_workflow — the agent-edited adapter for the eval harness.
#
# The JS reference returns ONLY the resolved model id. The agent's job is to
# extend this with a `source` field showing which precedence rule fired:
#   - "module"   if module override matched
#   - "aspect"   if aspect override matched
#   - "default"  if global default matched
#   - "auto"     if everything fell through
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter for eval.py.

    Input:  { "policy": {default?, copilot?, transform?, finance?, crm?, docs?},
              "ctx":    {module?: str, aspect?: str} }
    Output: { "resolved_model": str, "source": str }
    """
    policy = input_data.get("policy", {})
    ctx = input_data.get("ctx", {})

    # Agent's first-move fix: track which precedence rule fired.
    # Mirrors the same rule order as resolve_model() but classifies the source.
    if policy is None:
        policy = {}
    if ctx is None:
        ctx = {}
    module = ctx.get("module")
    aspect = ctx.get("aspect")

    source = "auto"
    resolved = ""

    if module and module in MODULES:
        m = _pick(policy, module)
        if m:
            source = "module"
            resolved = m
    if not resolved and aspect and aspect in ASPECTS:
        a = _pick(policy, aspect)
        if a:
            source = "aspect"
            resolved = a
    if not resolved:
        d = _pick(policy, "default")
        if d:
            source = "default"
            resolved = d

    return {"resolved_model": resolved, "source": source}
