from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/phone-am/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

COUNTRY_CODE = "374"
NSN_LENGTH = 8

# 8-digit NSN, must start with 1-9 (not 0)
_NSN_RE = re.compile(r"^[1-9]\d{7}$")


def normalize_nsn(value: Any) -> str:
    """Normalize any common phone-input shape to the 8-digit NSN, or "" if invalid."""
    s = re.sub(r"\D", "", str("" if value is None else value))
    if s.startswith("00374"):
        s = s[5:]
    elif len(s) == 11 and s.startswith("374"):
        s = s[3:]
    elif len(s) == 9 and s.startswith("0"):
        s = s[1:]
    return s if _NSN_RE.match(s) else ""


def is_valid_armenian_phone(value: Any) -> bool:
    return normalize_nsn(value) != ""


def e164(value: Any) -> str | None:
    nsn = normalize_nsn(value)
    return f"+374{nsn}" if nsn else None


def format_phone(value: Any) -> str | None:
    nsn = normalize_nsn(value)
    return f"+374 {nsn[:2]} {nsn[2:]}" if nsn else None


# ---------------------------------------------------------------------------
# Adapter for the eval harness.
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter for eval.py. Takes {"phone": "<raw phone string>"}.

    Output:
      {
        "nsn":       str,   # 8-digit NSN or "" if invalid
        "valid":     bool,  # True iff nsn is non-empty
        "e164":      str|None,  # "+374XXXXXXXX" or None
        "formatted": str|None,  # "+374 XX XXXXXX" or None
      }
    """
    phone = input_data.get("phone") if isinstance(input_data, dict) else input_data
    nsn = normalize_nsn(phone)
    return {
        "nsn": nsn,
        "valid": nsn != "",
        "e164": e164(phone),
        "formatted": format_phone(phone),
    }
