from __future__ import annotations

"""Vendored from autoresearch-sboss@6c9a9149f1dc8b7a5430d542de19f564a078418c — examples/phone-ru/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

COUNTRY_CODE = "7"
NSN_LENGTH = 10

# 10-digit NSN, must start 3-9 (geographic 3-8, mobile 9).
# Russian NSNs never start with 0/1/2.
_NSN_RE = re.compile(r"^[3-9]\d{9}$")


def normalize_nsn(value: Any) -> str:
    """Normalize any common phone-input shape to the 10-digit NSN, or "" if invalid."""
    digits = re.sub(r"\D", "", str("" if value is None else value))
    nsn = ""
    if len(digits) == 11 and digits[0] == "8":
        nsn = digits[1:]  # domestic trunk form 8XXXXXXXXXX
    elif len(digits) == 11 and digits[0] == "7":
        nsn = digits[1:]  # E.164 form without + 7XXXXXXXXXX
    elif len(digits) == NSN_LENGTH:
        nsn = digits       # already bare NSN
    return nsn if _NSN_RE.match(nsn) else ""


def is_valid_russian_phone(value: Any) -> bool:
    return normalize_nsn(value) != ""


def e164(value: Any) -> str | None:
    nsn = normalize_nsn(value)
    return f"+{COUNTRY_CODE}{nsn}" if nsn else None


def format_phone(value: Any) -> str | None:
    nsn = normalize_nsn(value)
    if not nsn:
        return None
    area = nsn[0:3]
    block = nsn[3:6]
    pair1 = nsn[6:8]
    pair2 = nsn[8:10]
    return f"+{COUNTRY_CODE} ({area}) {block}-{pair1}-{pair2}"


# ===========================================================================
# Autoresearch eval entry point
# ===========================================================================
# eval_set items look like:
#   { "input": {"value": "..."}, "expected": {"nsn": "...", "valid": bool, "e164": "..."|null, "formatted": "..."|null} }
# All 4 functions are evaluated for every case (mirrors the phone-am pattern).

def validate(input: dict) -> dict:
    value = input.get("value")
    return {
        "nsn": normalize_nsn(value),
        "valid": is_valid_russian_phone(value),
        "e164": e164(value),
        "formatted": format_phone(value),
    }
