from __future__ import annotations

"""Vendored from autoresearch-sboss@6e01155a5932a5456995465ae761db8057f87089 — examples/settings-store/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import json
import os
from pathlib import Path
from typing import Any


DEFAULT_KEYS = ["default", "copilot", "transform", "finance", "crm", "docs"]


def _defaults(model_keys: list[str]) -> dict:
    return {
        "openrouterApiKey": "",
        "models": {k: "" for k in model_keys},
        "openNotebook": {"enabled": False, "baseUrl": "", "apiKey": ""},
    }


def _merge_settings(base: dict, patch: Any, model_keys: list[str]) -> dict:
    """Merge a patch into the base settings. Mirrors JS mergeSettings()."""
    out = {
        "openrouterApiKey": base.get("openrouterApiKey", ""),
        "models": dict(base.get("models", {})),
        "openNotebook": dict(base.get("openNotebook", {})),
    }
    if isinstance(patch, dict):
        if isinstance(patch.get("openrouterApiKey"), str):
            out["openrouterApiKey"] = patch["openrouterApiKey"].strip()
        if isinstance(patch.get("models"), dict):
            for key in model_keys:
                if isinstance(patch["models"].get(key), str):
                    out["models"][key] = patch["models"][key].strip()
        if isinstance(patch.get("openNotebook"), dict):
            on = patch["openNotebook"]
            cur = out["openNotebook"]
            if isinstance(on.get("enabled"), bool):
                cur["enabled"] = on["enabled"]
            if isinstance(on.get("baseUrl"), str):
                cur["baseUrl"] = on["baseUrl"].strip().rstrip("/")
            if isinstance(on.get("apiKey"), str):
                cur["apiKey"] = on["apiKey"].strip()
            out["openNotebook"] = cur
    return out


def _file_path(data_dir: str, file_name: str) -> str:
    return os.path.join(data_dir, file_name)


def get_settings(data_dir: str, file_name: str = "ai-settings.json",
                 model_keys: list[str] | None = None) -> dict:
    """Read settings from disk. Returns defaults on missing/invalid file."""
    keys = list(model_keys) if model_keys else DEFAULT_KEYS
    base = _defaults(keys)
    path = _file_path(data_dir, file_name)
    try:
        with open(path) as f:
            raw = json.load(f)
    except (FileNotFoundError, IsADirectoryError, json.JSONDecodeError, OSError):
        return base
    if not raw or not isinstance(raw, dict):
        return base
    return _merge_settings(base, raw, keys)


def update_settings(data_dir: str, patch: Any = None,
                    file_name: str = "ai-settings.json",
                    model_keys: list[str] | None = None) -> dict:
    """Write settings to disk atomically. Sets 0600 perms (best-effort on
    platforms without POSIX perms). Returns the new settings."""
    keys = list(model_keys) if model_keys else DEFAULT_KEYS
    current = get_settings(data_dir, file_name, keys)
    merged = _merge_settings(current, patch or {}, keys)
    os.makedirs(data_dir, exist_ok=True)
    path = _file_path(data_dir, file_name)
    with open(path, "w") as f:
        json.dump(merged, f, indent=2)
    try:
        os.chmod(path, 0o600)
    except (OSError, NotImplementedError):
        pass  # best-effort on non-POSIX
    return merged


def redacted_for_client(settings: dict) -> dict:
    """Safe projection for the browser: secrets become boolean *Set flags."""
    s = settings or {}
    on = s.get("openNotebook", {}) or {}
    return {
        "openrouterApiKeySet": bool(s.get("openrouterApiKey", "")),
        "models": dict(s.get("models", {})),
        "openNotebook": {
            "enabled": bool(on.get("enabled", False)),
            "baseUrl": on.get("baseUrl", ""),
            "apiKeySet": bool(on.get("apiKey", "")),
        },
    }


def resolve_model_policy(data_dir: str, file_name: str = "ai-settings.json",
                         model_keys: list[str] | None = None,
                         default_models: dict | None = None) -> dict:
    """Effective per-aspect policy: stored selection wins, else injected env
    default, else auto ("")."""
    keys = list(model_keys) if model_keys else DEFAULT_KEYS
    dm = default_models or {}
    stored = get_settings(data_dir, file_name, keys).get("models", {})
    return {k: ((stored.get(k) or "").strip() or dm.get(k, "")) for k in keys}


def defaults(model_keys: list[str] | None = None) -> dict:
    """Return the default settings object (no I/O)."""
    return _defaults(list(model_keys) if model_keys else DEFAULT_KEYS)


# ===========================================================================
# Autoresearch eval entry point
# ===========================================================================
# eval_set items look like:
#   { "input": {operation, dataDir, patch?, settings?, fileName?, modelKeys?, defaultModels?},
#     "expected": {"result": <value>} }
#
# The eval creates a fresh tmp data dir per test case and passes it in via
# dataDir. After the test, the eval cleans up the dir. Per-case field set:
# {result} only.

def _run_op(op: str, o: dict, data_dir: str) -> dict:
    """Dispatch a single operation against the given data_dir."""
    file_name = o.get("fileName", "ai-settings.json")
    model_keys = o.get("modelKeys")
    default_models = o.get("defaultModels") or {}

    if op == "getSettings":
        return get_settings(data_dir, file_name, model_keys)
    if op == "updateSettings":
        return update_settings(data_dir, o.get("patch") or {}, file_name, model_keys)
    if op == "redactedForClient":
        s = o.get("settings") or get_settings(data_dir, file_name, model_keys)
        return redacted_for_client(s)
    if op == "resolveModelPolicy":
        return resolve_model_policy(data_dir, file_name, model_keys, default_models)
    if op == "defaults":
        return defaults(model_keys)
    return None


def validate(input: dict) -> dict:
    """Run a sequence of operations against a shared dataDir, return the result
    of the last operation. Single-op inputs work the same as a 1-element sequence.

    input:
      operations: list of {operation, ...args}  (optional; default = [input])
      dataDir:    shared across all operations in the sequence
    """
    o = input or {}
    data_dir = o.get("dataDir")
    operations = o.get("operations")
    if not operations:
        # Single-op form: treat the input itself as the one op
        operations = [o]

    last = None
    for op_in in operations:
        op = op_in.get("operation")
        last = _run_op(op, op_in, data_dir)
    return {"result": last}
