from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/sg-uen/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

UEN_MIN_LENGTH = 9
UEN_MAX_LENGTH = 10
_SEPARATOR_RE = re.compile(r"[\s\-]")
_ALNUM_RE = re.compile(r"^[A-Z0-9]+$")
_ALL_SAME_RE = re.compile(r"^(\w)\1{8,9}$")  # 9-10 of the same char
# Standard UEN: 9 digits + 1 check letter (total 10)
_DIGITS_AND_LETTER_RE = re.compile(r"^\d{9}[A-Z]$")
# Or 9-10 digits (no letter)
_DIGITS_ONLY_RE = re.compile(r"^\d{9,10}$")


def normalize_uen(value: Any) -> str:
    """Strip whitespace + hyphens, uppercase. Returns "" for null/None.

    Examples:
      '201912345A'  -> '201912345A'
      '2019 12345 A' -> '201912345A'
      '2019-12345-A' -> '201912345A'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value)).upper()


def _default_kind(uen: str) -> bool:
    """Default kind verifier (currently accepts any 9-10 alphanumeric string).

    This is the documented TODO seam. The official ACRA kind validation
    goes here (e.g. "must be 9 digits + 1 letter" or "must be 10 digits").
    The agent's main lever is to implement this correctly.

    Args:
        uen: a 9-10 char alphanumeric string that has already passed length / digits / non-degenerate checks.

    Returns:
        True if the kind format is valid, False if not.
    """
    # TODO: implement official ACRA UEN kind validation.
    # See: https://www.acra.gov.sg/
    return True


def validate_uen(value: Any, *, kind_verifier=None) -> dict[str, Any]:
    """Validate a Singapore UEN. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        kind_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the kind error. Defaults to the local
            _default_kind (which currently accepts everything).

    Returns:
        { ok: bool, normalized: str, "error": str | None }
    """
    verifier = kind_verifier if kind_verifier is not None else _default_kind

    normalized = normalize_uen(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "UEN is required"}
    if not _ALNUM_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "UEN must be alphanumeric"}
    if len(normalized) not in (UEN_MIN_LENGTH, UEN_MAX_LENGTH):
        return {"ok": False, "normalized": normalized, "error": f"UEN must be {UEN_MIN_LENGTH} or {UEN_MAX_LENGTH} characters, got {len(normalized)}"}
    if _ALL_SAME_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "UEN is invalid (all characters are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "UEN format is invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "uen": "<raw UEN string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_uen(input_data.get("uen"))
