from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/supplemental-sources/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



from typing import Any

MAX_SUPPLEMENTAL_SOURCES = 3
SUPPLEMENTAL_EXCERPT_MAX = 280


def _collapse_whitespace(s: str) -> str:
    return " ".join(s.split())


def normalize_supplemental_sources(raw: Any, opts: dict | None = None) -> list[dict]:
    """Normalize a list of raw rows into advisory-only supplemental source
    objects, deduped by sourceUrl||title, sorted by score desc, capped at max."""
    if not isinstance(raw, list):
        return []
    max_items = MAX_SUPPLEMENTAL_SOURCES
    if isinstance(opts, dict) and isinstance(opts.get("max"), int):
        max_items = opts["max"]

    cleaned: list[dict] = []
    for row in raw:
        r = row if isinstance(row, dict) else {}
        title = _collapse_whitespace(str(r.get("title") or "Open Notebook")) or "Open Notebook"
        text_raw = r.get("text") or r.get("excerpt") or ""
        excerpt = _collapse_whitespace(str(text_raw))[:SUPPLEMENTAL_EXCERPT_MAX]
        if not excerpt:
            continue
        score = r.get("score") if isinstance(r.get("score"), (int, float)) else 0
        source_url = r.get("sourceUrl") if isinstance(r.get("sourceUrl"), str) else ""
        cleaned.append({
            "title": title,
            "excerpt": excerpt,
            "sourceUrl": source_url,
            "score": score,
            "origin": "open-notebook",
            "advisory": True,
        })

    cleaned.sort(key=lambda x: x["score"], reverse=True)

    # Dedupe on sourceUrl when present, else title; keep the highest-scored hit.
    seen: set[str] = set()
    out: list[dict] = []
    for row in cleaned:
        key = (row["sourceUrl"] or row["title"]).lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(row)
        if len(out) >= max_items:
            break
    return out


# ===========================================================================
# Autoresearch eval entry point
# ===========================================================================
# eval_set items look like:
#   { "input": {raw, max?}, "expected": {count, titles, excerpts, sourceUrls, scores, allAdvisory} }
# Per-case field set.

def validate(input: dict) -> dict:
    o = input or {}
    raw = o.get("raw") or []
    opts = {}
    if "max" in o:
        opts["max"] = o["max"]
    result = normalize_supplemental_sources(raw, opts if opts else None)
    return {
        "count": len(result),
        "titles": [r["title"] for r in result],
        "excerpts": [r["excerpt"] for r in result],
        "sourceUrls": [r["sourceUrl"] for r in result],
        "scores": [r["score"] for r in result],
        "allAdvisory": all(r.get("advisory") is True for r in result) if result else True,
    }
