from __future__ import annotations

"""Vendored from autoresearch-sboss@7a4bb9a5bed9669801070b9c022d27b7d7b625e7 — examples/uk-company/workflow.py.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""



import re
from typing import Any

# Valid 2-letter prefixes for UK company numbers (England & Wales, Scotland, NI, etc.)
_VALID_PREFIXES = frozenset({
    "SC",  # Scottish limited company
    "NI",  # Northern Irish limited company
    "OC",  # Limited Liability Partnership
    "SO",  # Scottish LLP
    "NC",  # Northern Irish LLP
    "FC",  # overseas company
    "SF",  # Scottish further education
    "NF",  # Northern Irish further education
})

UK_COMPANY_LENGTH = 8
_ALL_DIGITS_RE = re.compile(r"^[0-9]+$")
_PREFIXED_RE = re.compile(r"^([A-Z]{2})([0-9]{6})$")


def normalize_uk_company(value: Any) -> str:
    """Trim whitespace, uppercase. No internal separator stripping.

    Returns: "" for null/None.
    """
    if value is None:
        return ""
    return str(value).strip().upper()


def _is_valid_uk_company(value: str) -> bool:
    """Default validity check — 8 digits OR a valid prefix + 6 digits.

    The agent's job: extend this to cover all 9 patterns (currently handles 4):
    - 8 digits
    - SC + 6 digits
    - NI + 6 digits
    - OC + 6 digits
    (missing: SO, NC, FC, SF, NF)
    """
    if len(value) != UK_COMPANY_LENGTH:
        return False
    if _ALL_DIGITS_RE.match(value):
        return True
    m = _PREFIXED_RE.match(value)
    if not m:
        return False
    prefix = m.group(1)
    return prefix in _VALID_PREFIXES


def validate_uk_company(value: Any) -> dict[str, Any]:
    """Validate a UK Company Number. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).

    Returns:
        { ok: bool, normalized: str, error: str | None }
    """
    normalized = normalize_uk_company(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "UK Company Number is required"}
    if len(normalized) != UK_COMPANY_LENGTH:
        return {
            "ok": False,
            "normalized": normalized,
            "error": f"UK Company Number must be {UK_COMPANY_LENGTH} characters, got {len(normalized)}",
        }
    if not _is_valid_uk_company(normalized):
        return {
            "ok": False,
            "normalized": normalized,
            "error": "UK Company Number has an invalid format (must be 8 digits or SC/NI/OC/SO/NC/FC/SF/NF + 6 digits)",
        }
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def validate(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "uk_company": "<raw UK Company Number string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_uk_company(input_data.get("uk_company"))
