"""test_hhvh.py — focused tests for the HHVH (Armenian taxpayer ID) validator.

These tests are upstreamed from autoresearch-sboss/examples/hhvh/eval_set.json
(20 ground-truth cases, score 100.00/100.00 baseline + 100.00 after pre-norm
fix per upstream commit f893bfd).

The port itself is in src/a1_validator/_vendored/hhvh.py — generated by
scripts/_vendor.py from autoresearch-sboss@6e01155a5.

This test verifies the PORT preserves the 100% score against the upstream
ground-truth corpus. If hhvh regresses, this test fails.

Per AGENTS.md §3, vendored files should NOT be edited by hand — re-run
`python scripts/_vendor.py` after pulling upstream.

Sources:
- autoresearch-sboss/examples/hhvh/eval_set.json (canonical ground truth)
- autoresearch-sboss/examples/hhvh/workflow.py (upstream port, MIT)
- A1-Localization-AM/src/localization.js::validateHvhh() (JS source of truth)
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from a1_validator import hhvh


# Load upstream eval_set.json (ground truth corpus)
EVAL_SET_PATH = Path(__file__).parent.parent.parent / "autoresearch-sboss" / "examples" / "hhvh" / "eval_set.json"
EVAL_SET = json.loads(EVAL_SET_PATH.read_text()) if EVAL_SET_PATH.exists() else []


@pytest.mark.parametrize("case", EVAL_SET, ids=[f"case-{i+1:02d}" for i in range(len(EVAL_SET))])
def test_hhvh_matches_upstream_ground_truth(case):
    """Each upstream eval case must produce the expected result."""
    input_data = case["input"]
    expected = case["expected"]
    actual = hhvh(input_data)

    assert actual["ok"] == expected["ok"], (
        f"case {input_data} → ok mismatch: actual={actual['ok']}, expected={expected['ok']}, "
        f"error={actual['error']}"
    )
    assert actual["normalized"] == expected["normalized"]
    assert actual["error"] == expected["error"]


def test_hhvh_canonical_3_3_2_grouping():
    """HHVH accepts canonical human-typed format '001-234-56' (3+3+2)."""
    assert hhvh({"hvhh": "001-234-56"}) == {"ok": True, "normalized": "00123456", "error": None}
    assert hhvh({"hvhh": "001.234.56"}) == {"ok": True, "normalized": "00123456", "error": None}
    assert hhvh({"hvhh": "001 234 56"}) == {"ok": True, "normalized": "00123456", "error": None}


def test_hhvh_rejects_typo_with_separator():
    """HHVH rejects '00123-456' (5+3 typo) — pre-norm fix from upstream f893bfd."""
    r = hhvh({"hvhh": "00123-456"})
    assert r["ok"] is False
    assert "8" in r["error"]  # length error message


def test_hhvh_rejects_degenerate():
    """HHVH rejects all-same-digit strings (00000000, 11111111, etc.)."""
    for value in ["00000000", "11111111", "99999999"]:
        r = hhvh({"hvhh": value})
        assert r["ok"] is False
        assert "անվավեր" in r["error"].lower() or "invalid" in r["error"].lower() or "պարտադիր" in r["error"]


def test_hhvh_rejects_non_digits():
    """HHVH rejects inputs with non-digit characters (after normalization)."""
    assert hhvh({"hvhh": "0012345A"})["ok"] is False
    assert hhvh({"hvhh": "ABCDEFGH"})["ok"] is False


def test_hhvh_rejects_empty():
    """HHVH rejects empty / whitespace-only input."""
    assert hhvh({"hvhh": ""})["ok"] is False
    assert hhvh({"hvhh": "   "})["ok"] is False
    assert hhvh({"hvhh": None})["ok"] is False


def test_hhvh_accepts_well_known_fixtures():
    """HHVH accepts all 8-digit ground-truth values (96.67 baseline + 100% fix)."""
    for value in ["00123456", "12345678", "00000001", "99999998"]:
        r = hhvh({"hvhh": value})
        assert r["ok"] is True, f"{value} should be valid: {r}"
        assert r["normalized"] == value
        assert r["error"] is None
