#!/usr/bin/env python3
"""Vendor script: copies the 23 workflow.py files into src/a1_validator/_vendored/<name>.py
and strips the run_workflow name in favor of a uniform `validate` function.

Run from the repo root after pulling the latest autoresearch-sboss:
    python scripts/_vendor.py
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AUTORESEARCH = REPO_ROOT.parent / "autoresearch-sboss"
VENDORED_DIR = REPO_ROOT / "src" / "a1_validator" / "_vendored"
SOURCE_COMMIT = "7a4bb9a5bed9669801070b9c022d27b7d7b625e7"

# (example_name, source_path_relative_to_autoresearch)
EXAMPLES = [
    ("hhvh",                 "examples/hhvh/workflow.py"),
    ("ru_identifiers",       "examples/ru-identifiers/workflow.py"),
    ("model_policy",         "examples/model-policy/workflow.py"),
    ("vat_return",           "examples/vat-return/workflow.py"),
    ("payroll_am",           "examples/payroll-am/workflow.py"),
    ("chart_of_accounts_am", "examples/chart-of-accounts-am/workflow.py"),
    ("vat_return_form",      "examples/vat-return-form/workflow.py"),
    ("phone_am",             "examples/phone-am/workflow.py"),
    ("regions_am",           "examples/regions-am/workflow.py"),
    ("einvoice_am",          "examples/einvoice-am/workflow.py"),
    ("chat_client",          "examples/chat-client/workflow.py"),
    ("phone_ru",             "examples/phone-ru/workflow.py"),
    ("ru_einvoice",          "examples/ru-einvoice/workflow.py"),
    ("payroll_ru",           "examples/payroll-ru/workflow.py"),
    ("regions_ru",           "examples/regions-ru/workflow.py"),
    ("chart_of_accounts_ru", "examples/chart-of-accounts-ru/workflow.py"),
    ("vat_ru",               "examples/vat-ru/workflow.py"),
    ("settings_store",       "examples/settings-store/workflow.py"),
    ("model_catalog",        "examples/model-catalog/workflow.py"),
    ("supplemental_sources", "examples/supplemental-sources/workflow.py"),
    ("open_notebook",        "examples/open-notebook/workflow.py"),
    ("product_research",     "examples/product-research/workflow.py"),
    ("invoice",              "workflow.py"),
    ("eu_vat",              "examples/eu-vat/workflow.py"),
    ("cnpj",                "examples/cnpj/workflow.py"),
    ("cpf",                 "examples/cpf/workflow.py"),
    ("uk_company",          "examples/uk-company/workflow.py"),
    ("us_ein",              "examples/us-ein/workflow.py"),
    ("gstin",               "examples/gstin/workflow.py"),
    ("swiss_uid",           "examples/swiss-uid/workflow.py"),
    ("au_abn",              "examples/au-abn/workflow.py"),
    ("mx_rfc",              "examples/mx-rfc/workflow.py"),
    ("jp_mynumber",         "examples/jp-mynumber/workflow.py"),
    ("ar_cuit",             "examples/ar-cuit/workflow.py"),
    ("cl_rut",              "examples/cl-rut/workflow.py"),
    ("sg_uen",              "examples/sg-uen/workflow.py"),
    ("kr_brn",              "examples/kr-brn/workflow.py"),
]




def header(name: str, source_rel: str) -> str:
    return f'''"""Vendored from autoresearch-sboss@{SOURCE_COMMIT} — {source_rel}.

This file is auto-generated by scripts/_vendor.py. DO NOT EDIT BY HAND --
re-run the vendor script after pulling upstream. The original `run_workflow`
eval-harness adapter has been renamed to `validate` (a uniform entry point)
so the module exposes a clean public API.
"""


'''


def insert_header(text: str, name: str, source_rel: str) -> str:
    """Replace the source's original module docstring with the vendored header.

    The original docstrings reference `workflow.py` which is no longer the
    module path -- they would mislead downstream readers. We strip the first
    docstring (which is always the module docstring at the top) and inject
    the vendored header right after the `from __future__` import.
    """
    hdr = header(name, source_rel)
    lines = text.splitlines(keepends=True)

    # Strip the original module docstring (a leading triple-quoted block, if any).
    body_start = 0
    if lines and lines[0].lstrip().startswith('"""'):
        # Find the closing triple-quote on its own line (or same line as open).
        first = lines[0]
        stripped = first.lstrip()
        # single-line docstring: """text"""
        if stripped.count('"""') >= 2 and stripped.rstrip().endswith('"""'):
            body_start = 1
        else:
            for i in range(1, len(lines)):
                if '"""' in lines[i]:
                    body_start = i + 1
                    break

    body = "".join(lines[body_start:]).lstrip("\n")

    # Ensure `from __future__` is first; if absent, add it.
    if not body.startswith("from __future__"):
        body = "from __future__ import annotations\n\n" + body

    # Now insert header AFTER the future-import line.
    out: list[str] = []
    inserted = False
    for line in body.splitlines(keepends=True):
        out.append(line)
        if not inserted and line.startswith("from __future__"):
            out.append("\n")
            out.append(hdr)
            inserted = True
    return "".join(out)


def transform(src: str, name: str) -> str:
    """Rename `def run_workflow(...)` -> `def validate(...)` (uniform name)
    and rewrite vendored data-file paths to the stem-named files.
    """
    out = re.sub(r"^def run_workflow\(", "def validate(", src, count=1, flags=re.MULTILINE)

    # Rewrite vendored data.json / sections.json paths to stem-namespaced copies
    # so multiple examples can coexist in one directory without clobbering each other.
    if name == "chart_of_accounts_am":
        out = out.replace('REPO_ROOT / "data.json"', 'REPO_ROOT / "chart_of_accounts_am.json"')
    elif name == "chart_of_accounts_ru":
        out = out.replace('"data.json"', '"chart_of_accounts_ru.json"')
        out = out.replace('"sections.json"', '"chart_of_accounts_ru_sections.json"')
    elif name == "regions_ru":
        out = out.replace('"data.json"', '"regions_ru.json"')

    return out


def main() -> int:
    if not AUTORESEARCH.exists():
        print(f"autoresearch-sboss not found at {AUTORESEARCH}", file=sys.stderr)
        return 1

    VENDORED_DIR.mkdir(parents=True, exist_ok=True)

    for name, rel in EXAMPLES:
        if name in SKIP_VENDOR:
            print(f"skipping {rel} (pinned in {name}.py)")
            continue
        src_path = AUTORESEARCH / rel
        if not src_path.exists():
            print(f"missing: {src_path}", file=sys.stderr)
            return 1

        text = src_path.read_text(encoding="utf-8")
        new_text = transform(text, name)
        out_path = VENDORED_DIR / f"{name}.py"
        out_path.write_text(insert_header(new_text, name, rel), encoding="utf-8")
        print(f"vendored {rel} -> _vendored/{name}.py  ({len(new_text.splitlines())} lines)")

    # Copy data files alongside vendored workflows so REPO_ROOT-relative loads work.
    # Rename each data file to the workflow stem to avoid collisions (multiple
    # examples ship their own data.json with different shapes).
    data_pairs = [
        (AUTORESEARCH / "examples/chart-of-accounts-am/data.json",
         VENDORED_DIR / "chart_of_accounts_am.json"),
        (AUTORESEARCH / "examples/chart-of-accounts-ru/data.json",
         VENDORED_DIR / "chart_of_accounts_ru.json"),
        (AUTORESEARCH / "examples/chart-of-accounts-ru/sections.json",
         VENDORED_DIR / "chart_of_accounts_ru_sections.json"),
        (AUTORESEARCH / "examples/regions-ru/data.json",
         VENDORED_DIR / "regions_ru.json"),
    ]
    for src, dst in data_pairs:
        if not src.exists():
            print(f"missing data file: {src}", file=sys.stderr)
            return 1
        shutil.copyfile(src, dst)
        print(f"vendored data {src.name} -> _vendored/{dst.name}")

    # Vendor the eval_set.json corpus so the test suite is self-contained.
    eval_dir = REPO_ROOT / "tests" / "_eval_sets"
    eval_dir.mkdir(parents=True, exist_ok=True)
    for name, rel in EXAMPLES:
        # The eval_set path is parallel to the workflow path: strip the
        # trailing workflow.py and append eval_set.json. The "invoice"
        # example lives at the repo root (not in examples/) — special-case
        # it to use the top-level eval_set.json.
        if name == "invoice":
            src = AUTORESEARCH / "eval_set.json"
        else:
            example_dir = rel.rsplit("/", 1)[0]
            src = AUTORESEARCH / example_dir / "eval_set.json"
        if not src.exists():
            print(f"missing eval_set: {src}", file=sys.stderr)
            return 1
        dst = eval_dir / f"{name}.json"
        shutil.copyfile(src, dst)
        print(f"vendored eval {src.name} -> tests/_eval_sets/{dst.name}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
